# Default values for socialmediawars.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

domains:
  server: api.socialmediawars.io
  client: socialmediawars.io
  altclient: alt.socialmediawars.io

apiUrls:
  http: https://api.socialmediawars.io
  ws: wss://api.socialmediawars.io

client:
  image:
    repository: socialmaulwars.azurecr.io/socialmediawars-client
    pullPolicy: Always    
    tag: "latest"
  service:
    type: ClusterIP
    port: 80

server:
  image:
    repository: socialmaulwars.azurecr.io/socialmediawars
    pullPolicy: Always    
    tag: "latest"   
  service:
    type: ClusterIP
    port: 80 

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:    
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

issuer:
  name: letsencrypt-production
  enabled: true
  email: ""
