apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"        
    {{ if .Values.issuer.enabled }}
    cert-manager.io/issuer: "letsencrypt-production"
    {{ end }}
spec:
  # if issuer is enabled
  {{ if .Values.issuer.enabled }}
  tls:
  - hosts:
    - {{ .Values.domains.client }}
    secretName: socialmediawars-client-tls  
  {{ end }}
  rules:  
  - host: {{ .Values.domains.client }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: socialmediawars-client
            port:
              number: 80