apiVersion: v1
kind: Service
metadata:
  name: {{ include "socialmediawars.fullname" . }}
  labels:
    {{- include "socialmediawars.labels" . | nindent 4 }}
    app.kubernetes.io/name: socialmediawars-server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "socialmediawars.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: socialmediawars-server
