name : Build SocialMediaWars Docker Image and Push it to ACR

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  golang-ci:
    name: Run Golang Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  golang-test:
    name: Run Golang Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  

      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
        
      - name: Run tests
        run: go test -v ./...

  buildJob:
    name: Build SocialMediaWars Docker Images and Push it to ACR
    runs-on: ubuntu-latest
    needs: [golang-ci, golang-test]
    steps:
      - uses: actions/checkout@v3

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build the Docker for server code      
        run: |
          docker build -f Dockerfile.server -t ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars:latest .          
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars:latest

      - name: Build the Docker for client code
        run: |
          docker build -f Dockerfile.client -t ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:latest .          
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:latest