name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  golang-ci:
    name: Run Golang Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

  golang-test:
    name: Run Golang Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Run tests
        run: go test -v ./...

  build-and-deploy:
    name: Build Docker Images and Deploy
    runs-on: ubuntu-latest
    needs: [golang-ci, golang-test]
    steps:
      - uses: actions/checkout@v3

      - uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build server image
        run: |
          docker build -f Dockerfile.server -t ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars:latest

      - name: Build client image
        run: |
          docker build -f Dockerfile.client -t ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Server App via Container Apps Action
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ secrets.ACR_LOGIN_SERVER_NAME }}
          containerAppName: ${{ secrets.SERVER_APP }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars:latest
          # registryUsername: ${{ secrets.ACR_USERNAME }}
          # registryPassword: ${{ secrets.ACR_PASSWORD }}

      - name: Deploy Client App via Container Apps Action
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ secrets.ACR_LOGIN_SERVER_NAME }}
          containerAppName: ${{ secrets.CLIENT_APP }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:latest
          # registryUsername: ${{ secrets.ACR_USERNAME }}
          # registryPassword: ${{ secrets.ACR_PASSWORD }}

