name: Build Preview for Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  golang-ci:
    name: Run Golang Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

  golang-test:
    name: Run Golang Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run tests
        run: go test -v ./...

  build-and-deploy-preview:
    name: Build Docker Images and Deploy Preview
    runs-on: ubuntu-latest
    needs: [golang-ci, golang-test]
    steps:
      - uses: actions/checkout@v3

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build server image
        run: |
          docker build -f Dockerfile.server -t ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars:pr-${{ github.event.number }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars:pr-${{ github.event.number }}

      - name: Build client image
        run: |
          docker build -f Dockerfile.client -t ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:pr-${{ github.event.number }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:pr-${{ github.event.number }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy preview Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp update --name ${{ secrets.SERVER_APP }}-pr-${{ github.event.number }} --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars:pr-${{ github.event.number }} || \
            az containerapp create --name ${{ secrets.SERVER_APP }}-pr-${{ github.event.number }} --resource-group ${{ secrets.RESOURCE_GROUP }} --environment ${{ secrets.CONTAINERAPPS_ENVIRONMENT }} --image ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars:pr-${{ github.event.number }} --target-port 8080 --ingress external
            az containerapp update --name ${{ secrets.CLIENT_APP }}-pr-${{ github.event.number }} --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:pr-${{ github.event.number }} || \
            az containerapp create --name ${{ secrets.CLIENT_APP }}-pr-${{ github.event.number }} --resource-group ${{ secrets.RESOURCE_GROUP }} --environment ${{ secrets.CONTAINERAPPS_ENVIRONMENT }} --image ${{ secrets.ACR_LOGIN_SERVER }}/socialmediawars-client:pr-${{ github.event.number }} --target-port 80 --ingress external
